import React from 'react';

function Courses() {
  return (
    <div>
      <h1>Courses</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut semper risus, eu pretium elit. Nullam hendrerit rutrum tortor vitae commodo. Ut sed gravida tortor. Curabitur consequat lectus dolor, eu ultricies tortor malesuada vitae. Nam vehicula lectus mauris, placerat finibus ipsum gravida sit amet. Aliquam diam tortor, volutpat et mauris at, porta placerat ipsum. Maecenas in tortor id lectus efficitur mattis. Mauris interdum enim vitae erat rutrum varius vel id odio. Nullam sit amet porta mi. Nam ex urna, congue ut dolor at, dignissim eleifend tellus. Pellentesque dui lorem, scelerisque quis felis eget, sollicitudin tristique libero. Donec ornare sem vel purus dignissim, quis fermentum quam mattis. Fusce sed vulputate felis. Quisque est nisi, euismod vehicula leo sit amet, imperdiet varius magna. Nullam ut turpis in erat placerat congue vel eget sapien.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut semper risus, eu pretium elit. Nullam hendrerit rutrum tortor vitae commodo. Ut sed gravida tortor. Curabitur consequat lectus dolor, eu ultricies tortor malesuada vitae. Nam vehicula lectus mauris, placerat finibus ipsum gravida sit amet. Aliquam diam tortor, volutpat et mauris at, porta placerat ipsum. Maecenas in tortor id lectus efficitur mattis. Mauris interdum enim vitae erat rutrum varius vel id odio. Nullam sit amet porta mi. Nam ex urna, congue ut dolor at, dignissim eleifend tellus. Pellentesque dui lorem, scelerisque quis felis eget, sollicitudin tristique libero. Donec ornare sem vel purus dignissim, quis fermentum quam mattis. Fusce sed vulputate felis. Quisque est nisi, euismod vehicula leo sit amet, imperdiet varius magna. Nullam ut turpis in erat placerat congue vel eget sapien.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut semper risus, eu pretium elit. Nullam hendrerit rutrum tortor vitae commodo. Ut sed gravida tortor. Curabitur consequat lectus dolor, eu ultricies tortor malesuada vitae. Nam vehicula lectus mauris, placerat finibus ipsum gravida sit amet. Aliquam diam tortor, volutpat et mauris at, porta placerat ipsum. Maecenas in tortor id lectus efficitur mattis. Mauris interdum enim vitae erat rutrum varius vel id odio. Nullam sit amet porta mi. Nam ex urna, congue ut dolor at, dignissim eleifend tellus. Pellentesque dui lorem, scelerisque quis felis eget, sollicitudin tristique libero. Donec ornare sem vel purus dignissim, quis fermentum quam mattis. Fusce sed vulputate felis. Quisque est nisi, euismod vehicula leo sit amet, imperdiet varius magna. Nullam ut turpis in erat placerat congue vel eget sapien.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut semper risus, eu pretium elit. Nullam hendrerit rutrum tortor vitae commodo. Ut sed gravida tortor. Curabitur consequat lectus dolor, eu ultricies tortor malesuada vitae. Nam vehicula lectus mauris, placerat finibus ipsum gravida sit amet. Aliquam diam tortor, volutpat et mauris at, porta placerat ipsum. Maecenas in tortor id lectus efficitur mattis. Mauris interdum enim vitae erat rutrum varius vel id odio. Nullam sit amet porta mi. Nam ex urna, congue ut dolor at, dignissim eleifend tellus. Pellentesque dui lorem, scelerisque quis felis eget, sollicitudin tristique libero. Donec ornare sem vel purus dignissim, quis fermentum quam mattis. Fusce sed vulputate felis. Quisque est nisi, euismod vehicula leo sit amet, imperdiet varius magna. Nullam ut turpis in erat placerat congue vel eget sapien.</p>
    </div>
  )
}

export default Courses;